version: '1'
services:
  # Node.js service
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3002"
    depends_on:
      - mongo
    networks:
      - app-network

  # MongoDB service
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  # mongo-express service
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge